name: Tests
on:
  push:
    branches: 
      - master
  pull_request:
    types: [opened, synchronize]
jobs:
  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Credentials
      run: |
        git config --global credential.helper store
        echo "https://AnTonhoLAB:${{ secrets.ACCESS_TOKEN }}@github.com" > ~/.git-credentials
    - name: Pod Install
      run: pod install
    - name: Run tests
      run: xcodebuild clean test -workspace PokeWiki.xcworkspace -scheme PokeWiki -destination "platform=iOS Simulator,name=iPhone 12 Pro,OS=latest"
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1.2.1
